/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: Right985
 * Time: 2021-12-26 21:39:50
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
const int N = 1e6;
ll a[N];

int main() {
    ios::sync_with_stdio(false);
    cin.tie(0);
    ll t, w, h, k, ans, tmp;
    cin >> t;
    while(t--) {
        ans = 0;
    	cin >> w >> h;
    	for(ll i = 0; i < 4; i++) {
    	    cin >> k;
    	    for (ll j = 0; j < k; j++) cin >> a[j];
    	    tmp = (a[k-1] - a[0]) * (i < 2 ? h : w);
    	    ans = ans > tmp ? ans : tmp;
    	}
    	cout << ans << endl;
    }
    
    return 0;
}
