/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: Right985
 * Time: 2022-01-14 19:45:33
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;

int main() {
    ios::sync_with_stdio(false);
    cin.tie(0);
    int t, n;
    ll a, b, c;
    cin >> t;
    while(t--) {
        cin >> n;
        a = -1;
        b = 1e9+1;
        for (int i = 0; i < n; i++){
        cin >> c;
        a = a > c ? a : c;
        b = b < c ? b : c;
        }
        cout << a - b << endl;
    }
    return 0;
}
