/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: Right985
 * Time: 2021-12-26 22:40:38
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
const int N = 500 * 1000 + 13;

int main() {
    ios::sync_with_stdio(false);
    cin.tie(0);
    int q;
    cin >> q;
    vector<int> t(q), x(q), y(q);
    for (int i = 0; i < q; i++) {
        cin >> t[i] >> x[i];
        if (t[i] == 2) cin >> y[i];
    }
    vector<int> p(N);
    iota(p.begin(), p.end(), 0);
    vector<int> ans;
    for (int i = q - 1; i >= 0; i--) {
      if (t[i] == 1) {
          ans.push_back(p[x[i]]);
      } else {
          p[x[i]] = p[y[i]];
      }
    }
    reverse(ans.begin(), ans.end());
    for (int &x: ans) cout << x << " ";
    return 0;
}
