/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: Right985
 * Time: 2022-01-14 20:47:46
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;

int main() {
    ios::sync_with_stdio(false);
    cin.tie(0);
    int t;
    cin >> t;
    for (int _ = 0; _ < t; ++_) {
        int n, k;
        string s;
        cin >> n >> k >> s;
        vector<int> cnt(26);
        for (char c : s) {
            cnt[c - 'a']++;
        }
        int cntPairs = 0, cntOdd = 0;
        for (int c : cnt) {
            cntPairs += c / 2;
            cntOdd += c % 2;
        }
        int ans = 2 * (cntPairs / k);
        cntOdd += 2 * (cntPairs % k);
        if (cntOdd >= k) {
            ans++;
        }
        cout << ans << '\n';
    }
    return 0;
}
