/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: Right985
 * Time: 2022-01-01 21:43:13
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
int a[105];

int main() {
    ios::sync_with_stdio(false);
    cin.tie(0);
    int t, n, x, ans;
    cin >> t;
    while(t--) {
    	cin >> n;
    	ans = 0;
    	memset(a, 0, sizeof(a));
    	for (int i = 0; i < n; i++) {
    		cin >> x;
    		x = x > 0 ? x : -x;
    		if (a[x] == 0) {
    			a[x] += 1;
    			ans += 1;
    		}
    		else if (a[x] == 1 && x) {
    			a[x] += 1;
    			ans += 1;
    		}
    		
    	}
    	cout << ans << std::endl;
    }
    return 0;
}
